More deploy work

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -2,6 +2,9 @@
 
 # This is run on the server to deploy the dockerized kernel, to synchronize the repositories, and to reload on error
 ROOT="$HOME/root"
+BOOT="$HOME/root/boot"
+SRC="$HOME/root/usr/src/kernel"
+
 SYNC="$ROOT/boot/lib/git-sync"
 
 if [ ! -x "$SYNC" ]; then
@@ -9,14 +12,45 @@ if [ ! -x "$SYNC" ]; then
   exit 1
 fi
 
-sync_root() {
-  pushd "$ROOT"
-  
-  $SYNC
+sync() {
+  pushd "$BOOT"
+
+  if ! $SYNC; then
+    echo "Sync failed for boot, aborting."
+    return 1
+  fi
+
+  git checkout master
+
+  popd
+
+  pushd $SRC
+
+  if ! $SYNC; then
+    echo "Sync failed for kernel, aborting."
+    return 2
+  fi
+
+  git checkout master
+
+  popd
+
+  pushd $ROOT
+
+  if ! $SYNC; then
+    echo "Sync failed for root, aborting."
+    return 3
+  fi
+
+  git checkout master
 
   popd
 }
 
 echo "Deploy script running on remote server."
 
-sync_root
+if sync; then
+  echo "Sync was successful"
+else
+  echo "Sync failed"
+fi
